{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soketi.fullname" . }}
  labels:
    {{- include "soketi.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "soketi.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: "9601"
      interval: {{ .Values.serviceMonitor.scrapeInterval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
